language: php

php:
  - 7.3.5

env:
  global:
    - CI_HOST=ftp.deakin.edu.au

stages:
  - name: Quality
  - name: Build
    if: branch = develop AND type = merge
  - name: Deploy
    if: branch = develop AND type = merge

before_script:
  - composer self-update
  - composer require
  - yarn

jobs:
  include:
    - stage: Quality
      script: composer lint
    - stage: Quality
      script: composer test
    - stage: Build
      script: composer build
    - stage: Deploy
      script: composer deploy

notifications:
  on_success: never
  on_failure: never