language: php

php:
  - 7.3.5

env:
  global:
    - CI_HOST=ftp.deakin.edu.au

stages:
  - name: Quality
  - name: Deploy
    if: head_branch = develop

before_script:
  - composer self-update
  - composer require
  - yarn

jobs:
  include:
    - stage: Quality
      name: "Lint"
      script: composer lint
    - stage: Quality
      name: "Unit Tests"
      script: composer test
    - stage: Deploy
      name: "Deploy"
      script: composer deploy

notifications:
  on_success: never
  on_failure: never